Feat/cards
Valtakausi/vk-ts pull request #119
Opened 2021-01-13 21:27 UTC by PetePetelius

2021-01-14 18:13 UTC, bensku requested changes

2021-01-14 18:13 UTC, bensku commented on src/games/cards.ts
> +const SHUFFLE_COOLDOWNS = new Set<Player>();
```suggestion
const shuffleCooldowns = new Set<Player>();
```
Because this set changes, it should not be named like constants.

2021-01-14 18:13 UTC, bensku commented on src/games/cards.ts
> +const FULL_DECK = new CustomItem({
```suggestion
const FullDeck = new CustomItem({
```
Custom items have been named as classes. Aside doing it the same way everywhere, it helps distinguish them from constants (e.g. CARDS) and mutable top-level variables (e.g. shuffleCooldows, see my suggestion above).

2021-01-14 18:13 UTC, bensku commented on src/games/cards.ts
> +function ClickedOnce(
```suggestion
function clickedOnce(
```
This should use normal function naming.

2021-01-14 18:13 UTC, bensku commented on src/games/cards.ts
> +  if (!(sender instanceof Player)) return;
Use registerCommand options to make the command executable by players only.

2021-01-14 18:13 UTC, bensku commented on src/games/cards.ts
> +  if (!player.isOp()) return;
By default, CraftJS restricts commands to ops.

2021-01-16 18:15 UTC, Laetta approved these changes

2021-01-16 18:15 UTC, merged