feat: add breeding
Valtakausi/vk-ts pull request #61
Opened 2020-11-24 14:45 UTC by PetePetelius

2020-11-24 15:02 UTC, Laetta commented on src/misc/breeding.ts
> +        block.setBlockData(data);
replace setters and getters ->

block.setType(...)   ->  block.type = ...

block.setBlockData(...)  --> block.blockdata = ...

2020-11-29 13:41 UTC, bensku requested changes

2020-11-29 13:41 UTC, bensku commented on src/misc/breeding.ts
> +function hasFoodSource(entity: LivingEntity): boolean {
This consumes the nearby food source, and the name should indicate that.

2020-11-29 13:41 UTC, bensku commented on src/misc/breeding.ts
> +function hasWaterSource(entity: LivingEntity): boolean {
This also consumes water, name should not begin with 'has'.

2020-11-29 13:41 UTC, bensku commented on src/misc/breeding.ts
> +function blocksInRadiusOfEntity(entity: LivingEntity, radius: number): Block[] {
Note to self: unified API for iterating blocks around entity/location.

2020-11-29 13:41 UTC, bensku commented on src/misc/breeding.ts
> +  if (!hasFood || !hasWater) baby.remove();
If only food or only water is available, it will be consumed when breeding fails. Is this intentional?

2020-12-13 14:57 UTC, bensku approved these changes

2021-01-15 06:47 UTC, Laetta commented on src/misc/breeding.ts
> +  if (!isFed || !isHydrated) baby.remove();
This was designed to be intentional

2021-01-15 06:58 UTC, merged